# Regularization

In [4]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
insurance = pd.read_csv("C:\\Users\\obay\\Downloads\\archive (4)\\insurance.csv")
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [6]:
# change sex column to numerical (1=Male, 0=Female)
insurance = insurance.drop('region', axis=1)
insurance['sex']=insurance['sex'].apply(lambda x: 1 if x=='male' else 0)
# change smoker to numerical (1=yes, 0=no)
insurance['smoker']=insurance['smoker'].apply(lambda x: 1 if x=='yes' else 0)

insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   int64  
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   int64  
 5   charges   1338 non-null   float64
dtypes: float64(2), int64(4)
memory usage: 62.8 KB


In [7]:
X_1 = insurance.drop('charges',axis=1)

In [8]:
y_1 = insurance['charges']

In [9]:
from sklearn.preprocessing import PolynomialFeatures

In [10]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [11]:
poly_features = polynomial_converter.fit_transform(X_1)

In [12]:
print(X_1.shape)
print('\n')
print('\n')
print(poly_features.shape)

(1338, 5)




(1338, 55)


In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y_1, test_size=0.3, random_state=101)

In [15]:
print(X_train.shape)
print('\n')
print(X_test.shape)

(936, 55)


(402, 55)


In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()

In [18]:
scaler.fit(X_train) # only fit the data to the training set in order to avoid data leakage from the test_sets

StandardScaler()

In [19]:
X_train = scaler.transform(X_train)

In [20]:
X_test = scaler.transform(X_test)

In [21]:
X_train[0]

array([ 0.92799531, -1.01724265,  1.24941097,  0.75674405, -0.52625475,
        0.87710995, -0.90420736,  1.51592015,  1.19491548, -0.48876173,
       -1.01724265, -0.97957369, -0.56225353, -0.37796447,  1.26082451,
        1.13877192, -0.51273082,  0.32258592, -0.34579766, -0.52625475,
        0.78374455, -0.74076703,  1.31914032,  1.39492237, -0.42350813,
       -0.90420736, -0.86671881, -0.53646473, -0.35261831,  1.71389592,
        1.60026247, -0.47672956,  0.60478175, -0.33205552, -0.48876173,
       -1.01724265, -0.97957369, -0.56225353, -0.37796447, -0.88570229,
       -0.55690495, -0.37039978, -0.41161272, -0.26497889, -0.37796447,
        1.22443127,  1.40804379, -0.47771493,  0.55400445, -0.34083125,
       -0.51273082,  0.02492948, -0.27546577, -0.34579766, -0.52625475])

In [22]:
from sklearn.linear_model import Ridge

In [23]:
ridge_model = Ridge(alpha=10)

In [24]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [25]:
test_predictions = ridge_model.predict(X_test)

In [26]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [27]:
MAE = mean_absolute_error(y_test, test_predictions)

In [28]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [29]:
print(MAE)
print('\n')
print('\n')
print(RMSE)

2851.2712649519194




4702.955226061636


In [30]:
from sklearn.linear_model import RidgeCV  # Used for cross validation. the best alpha score will be used 

In [31]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [32]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [33]:
ridge_cv_model.alpha_

0.1

In [34]:
from sklearn.metrics import SCORERS

In [35]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [36]:
test_predictions = ridge_cv_model.predict(X_test)

In [37]:
MAE = mean_absolute_error(y_test, test_predictions)
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

print(MAE)
print('\n')
print('\n')
print(RMSE)

2841.898612551231




4771.485253908453


In [38]:
ridge_cv_model.coef_

array([ -4380.77292259,   -749.74556643,  -9121.25265649,   4411.27775051,
        -4433.45648226,   9967.53698903,   2124.39107117,   2911.94362441,
       -14396.88839364,  -1010.33931461,   -749.74556643,    413.93842616,
          -65.81823808,   -582.94098023,  19693.59727943,   5050.91445933,
        15926.26737471,    607.06201315,    455.70080113,  -4433.45648226,
        -1891.71878537,   -790.81696904,  -3356.12059679,   6668.67307804,
        -1519.7310167 ,   2124.39107117,  -3289.8680489 ,     34.64087546,
         1385.84119131,    950.26540909,   1938.84779481,   2984.34995144,
         2546.3215317 ,     46.06359937,  -1010.33931461,   -749.74556643,
          413.93842616,    -65.81823808,   -582.94098023,    985.59216679,
          391.70975623,    217.00434324,   -359.77641979,   -505.14822443,
         -582.94098023, -11744.6514035 ,  -3049.26774419,  -8014.30131721,
        -1799.71023822,  -1067.83183926,  15926.26737471,   -681.57045884,
          224.72944555,  

# LASSO - Least Absolute Shrinkage and Selection Operator

In [39]:
from sklearn.linear_model import LassoCV?

Object `LassoCV` not found.


In [ ]:
from sklearn.linear_model import LassoCV

In [40]:
from sklearn.linear_model import LassoCV

In [41]:
from sklearn.linear_model import LassoCV

In [42]:
lasso_cv_model = LassoCV(eps=0.1,n_alphas=100,cv=5)

In [43]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [44]:
lasso_cv_model.alpha_

1047.473089092519

In [45]:
test_predictions = lasso_cv_model.predict(X_test)

In [46]:
MAE = mean_absolute_error(y_test, test_predictions)
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [47]:
print(MAE)
print('\n')
print('\n')
print(RMSE)

3432.5595371846134




5056.54244281514


In [48]:
lasso_cv_model.coef_

array([   0.        ,   -0.        ,    0.        ,    0.        ,
          0.        , 1535.78753173,    0.        ,    0.        ,
          0.        ,    0.        ,   -0.        ,   -0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
       1418.81246538,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,  953.69055313,   59.21794545,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,  869.02328716,
          0.        ,    0.        ,    0.        ,   -0.        ,
         -0.        ,    0.        ,    0.        ,   -0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        , 7236.84656621,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ])

In [49]:
from sklearn.linear_model import ElasticNetCV

In [50]:
elastic_model = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],eps=0.001, n_alphas=100,max_iter=1000000)

In [51]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [53]:
elastic_model.l1_ratio_

1.0

In [54]:
lasso_cv_model.alpha_

1047.473089092519

In [55]:
elastic_model.alpha_

10.47473089092519